- src/pages/KJS/test.html
> ✨ feat: typescript 폴더 추가

- test-khm.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #9
> 🧪 test: 테스트 코드 추가

- src/typescript/kjstest.ts
> 🧪test: 테스트 코드 추가

- src/pages/HYR/vote.css
- src/pages/HYR/vote.html
> 🔧 conf:설정파일 추가/수정

- src/pages/KHM/time/time.html
- src/typescript/time.ts
- test-khm.js
test 파일 삭제
개발 폴더 및 파일 생성
resolves #4
> 🔧 conf: 파일 추가 및 수정

- src/main.ts
- src/pages/HYR/modal.html
- src/pages/HYR/vote.html
- src/typescript/modal.js
- src/typescript/modal.ts
- src/typescript/vote.js
- src/typescript/vote.ts
> ✨feat: vote 기능 수정, modal 추가

- src/js/time.ts
> ✨ feat: timer 투표 지목 기능 추가

- src/js/SkilsTestState.ts
- src/js/jobSkils.ts
- src/js/mafiaSkils.ts
- src/pages/JobskilsTest.html
마피아 기능을 수정하였고 경찰 기능을 개발하였습니다.
resolves #39
> ✨ feat: 마피아 기능 보완 및 경찰 기능 개발

- src/pages/random-role-test.html
- src/pages/time.html
> ♻️ refactor: ts 경로 수정

- src/pages/chatlist-page.html
> ♻️ refactor : 모달창 , 입장 버튼 수정

- src/js/start-button-modal.ts
- src/pages/chatlist-page.html
- src/pages/server-page.html
- src/pages/start-page.html
시작페이지 - 서버페이지 - 채팅방목록페이지 연결
hidden flex 경고 수정
resolves #49
> ♻️ refactor: 페이지 연결 및 경고 수정

- src/js/chat/chat.ts
- src/js/chat/leave.ts
- src/js/chat/receive.ts
- src/js/chat/send.ts
- src/js/room/createRoom.ts
- src/js/room/enterRoom.ts
- src/js/room/roomList.ts
- src/js/server-page/server-page.ts
- src/js/socket.ts
- src/js/socket/socket.ts
- src/js/start-button-modal.ts
- src/pages/server-page.html
- src/pages/start-page.html
creat/ start with nickname
resolves #51
> create/ start with nickname

- src/js/start-button-modal.ts
- src/pages/start-page.html
♻️ refactor/start with nickname
resolves #56
> ♻️ refactor/start with nickname

- src/js/chat/chat.ts
- src/js/room/createRoom.ts
♻️ refactor/all nickname show host issue
resolves #58
> ♻️ refactor/all nickname show host issue

- src/js/chat/leave.ts
♻️ refactor/ maintain nickname although you get out the room
resolves #60
> ♻️ refactor/ maintain nickname although you get out the room

- src/js/server-page/server-page.ts
- src/pages/chatlist-page.html
> 💄 feat: 방생성 모달창 수정, 경로변경

- index.html
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #
> 🚚 file add : index.html

- src/js/chat/chat.ts
- [] 코드 리팩토링
- [] 문서 수정
resolves #73
> 🐛 fix: chat 코드 수정

- src/js/chat/chat.ts
- src/js/chat/chatting.ts
- src/js/lib/yongchat.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
♻️ DU/modify showing chat text
76
resolves #
> ♻️ DU/modify showing chat text

- src/js/chat/vote.ts
- src/js/lib/yongchat.ts
- src/pages/chat.html
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #62
> ✨ feat: vote

- src/js/chat/chat.ts
- src/js/chat/start.ts
- src/js/lib/yongchat.ts
- src/js/time.ts
- src/pages/chat.html
참가자들 타이머 밤부터 시작하도록 phase : night 설정
게임시작 버튼 누른 후 타이머 보이도록 수정
resolves #80
> ♻️ refactor: 밤 시작 설정, 타이머 초기화

- src/js/chat/vote.ts
- src/js/lib/yongchat.ts
- [] 코드 리팩토링
- [] 문서 수정
resolves #
> 🚧 vote: add

- src/js/time.ts
- x[] 커밋 메시지 컨벤션에 맞게 작성했습니다.
resolves #
> ♻️ refactor: export 수정

- src/js/time.ts
> ♻️ refacrot: export

- src/js/chat/chat.ts
- src/js/socket/socket.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #94
> 🐛 bug: delete unused variable  for netlify upload

- src/js/chat/liveordie.ts
- src/js/lib/yongchat.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
reject 파라미터 삭제
resolves #96
> 🐛 bug/delete reject parameter

- vite.config.js
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #98
> 🐎 distribution : 1차 테스트

- src/js/chat/chat.ts
- src/js/chat/chatting.ts
- src/js/time.ts
시간대 채팅에 알림
게임 시작 버튼을 눌러야 타이머 보이도록
+- 15초 기능 삭제
resolves #87
> ✨ feat: 자동 스크롤 기능 추가 / 시간대 알림

- src/js/chat/chat.ts
- src/js/chat/kill.ts
- src/js/chat/vote.ts
- src/js/lib/store.ts
- src/js/time.ts
낮, 밤 동안 투표 및 마피아 기능 행동 제어를 위해 time.ts에 canAct 변수를 추가하여 작성하였습니다.
> ✨ feat: 행동제어를 위한 기능 구현

- src/js/chat/chat.ts
- src/pages/chat.html
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
- [] 문서 수정
resolves #100
> 💄 style: chatting style add

- src/js/chat/chat.ts
- src/js/chat/chatting.ts
- src/pages/chat.html
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #
> 🚧 code add

- src/js/chat/chat.ts
- src/js/lib/yongchat.ts
- src/js/room/createRoom.ts
> ✨feat: 죽은 사람은 찬반투표 불가능하게 만드는 기능

- src/js/time.ts
두 번째 밤에도 마피아가 킬 기능을 수행할 수 있도록 코드를 수정했습니다.
> ♻️ refactor: 두번째 밤에도 마피아가 킬 가능하게 수정

- src/js/lib/store.ts
- src/js/time.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
안쓰는 함수명 변수 삭제
resolves #121
> ♻️refactor: modify-for-deploy

- src/js/chat/chat.ts
- src/js/time.ts
유저가 투표한 유저의 값을 알 수 있도록 기능을 구현했습니다.
> ✨ feat: 투표시 해당 투표한 유저 값 알 수 있도록하는 기능

- src/js/chat/vote.ts
- src/js/time.ts
- src/js/vote.ts
플레이어 모두가 투표하지 않아도 시간이 지나면 투표가 종료되게 끔 수정하였습니다.
> ♻️ refactor: 투표 수 표시 수정

- tsconfig.json
- vite.config.js
- [] 새로운 기능 추가
- [] 버그 수정
- [] 코드 리팩토링
target 2020 -> 2022 in vite.config , tsconfig
resolves #125
> 📝 docs: target 2020 -> 2022 in vite.config , tsconfig

- src/js/chat/vote.ts
> 🐛 fix: 배포 오류 수정

- src/pages/chatlist-page.html
chatlist.html에 tailwind을 import하는 구문이 빠져있어 추가하였습니다.
> ♻️ refactor: chatlist 페이지 코드 수정

- src/js/lib/yongchat.ts
yongchat.ts 파일에 배포를 위하여 ws-> wss로 수정하였습니다.
> ♻️ refactor: yongchat 파일 수정

- src/pages/chatting-page.html
- src/pages/modal.html
- src/pages/time.html
- src/pages/vote.html
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #
> 🐛 bug: 배포 수정

- src/js/chat/chat.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #
> 🐛 fix: 프로필 이미지 배포 문제

- src/js/chat/chat.ts
- src/js/chat/chatting.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
빈 문자열 보내면 안보내지도록
resolves #135
> ♻️ refactor: modify black chat

- src/js/chat/chat.ts
시작버튼 여러번 누를 수 있도록 수정
resolves #136
> ♻️ refactor: 게임 시작 버튼 비활성화 해제

- src/js/chat/victory.ts
- src/js/time.ts
게임 승리 조건 식을 세워 마피아의 승과 시민의 승을 구별하는 코드를 작성하였습니다.
> ✨ feat: 게임 승리 조건 개발

- src/js/chat/chat.ts
- src/js/chat/police.ts
- src/js/time.ts
> ✨ feat: 경찰 기능 추가

- src/js/chat/chat.ts
- src/js/chat/kill.ts
- src/js/chat/liveordie.ts
- src/js/time.ts
- src/pages/chat.html
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
liveordie  수정중
resolves #139
> ♻️ refactor:modify liveordie func

- src/js/chat/chat.ts
- src/js/chat/kill.ts
- src/js/chat/liveordie.ts
- src/js/lib/yongchat.ts
- src/js/time.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
refactor: modify liveordie func
resolves #154
> ♻️ refactor: modify liveordie func

- src/js/chat/chat.ts
- src/js/chat/kill.ts
- src/js/chat/vote.ts
- src/js/time.ts
- src/main.ts
배포를 위하여 사용하지 않는 변수 명, 파일을 삭제하였습니다.
> ♻️ refactor: 배포를 위한 코드 수정

- src/js/chat/chat.ts
- src/js/chat/chatting.ts
- src/js/time.ts
- [] 새로운 기능 추가
- [] 코드 리팩토링
- [] 문서 수정
resolves #
> 🐛 bug: 타임 버그수정
